version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress
    restart: always
    ports:
      - "${WEBSERVER_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress-backend

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress-backend

volumes:
  wordpress:
  db:

networks:
  wordpress-backend:
    driver: bridge